FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

COPY target/fidelity-0.0.1-SNAPSHOT.jar app.jar

ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_SERVER_PORT

ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
    SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL} \
    SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} \
    SPRING_SERVER_PORT=${SPRING_SERVER_PORT}

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]